config/routes.rb
Rails.application.routes.draw do

  root              'static_pages#home'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  get 'chat' => 'static_pages#chat'
  get 'video' => 'static_pages#video'

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "group_id",
                                  dependent:   :destroy
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user, class_name: "User"
  belongs_to :group, class_name: "Group"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "user_id",
                                  dependent:   :destroy
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

#this is really weird - why do i need to include this file? it was always auto-included in the sample app
include SessionsHelper

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    log_in user
    redirect_to chat_path
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/show_controller.rb
class ShowController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def chat
  end
  def video
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def logged_in?
		!current_user.nil?
	end

	def log_in(user)
    	session[:user_id] = user.id
  	end

  	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user?(user)
    	user == current_user
	end

	
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <!--<small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
        <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
    -->
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "benedictation", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        	<li><%= link_to "#{current_user.name}", chat_path %></li>
        	<li><%= link_to "Home",   root_path %></li>
          <li><%= link_to "Log out", signout_path, id: "sign_out" %></li>
      	<% else %>
      		<li><%= link_to "Home",   root_path %></li>
        	<li><%= link_to "Log in", "/auth/google_oauth2", id: "sign_in" %></li>
      	<% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Benedictation" %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/chat.html.erb
<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                        <%= link_to "Groups", '#' %>
                </li>
                <% Relationship.where(user_id: current_user.id).pluck(:id).each do |relationship_id| %>
                    <li>
                        <%= link_to "#{Relationship.find_by(id: relationship_id).group.group_name}", '#' %>
                    </li>
                <% end %>
                <li>
                   <%= link_to "[ create new group + ]", '#' %>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1>Start a group to begin chatting!</h1>
                        <p>Use the sidebar on the left to create a new group or to enter a group that has already been created.</p>
                        <!--<p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>-->
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Benedictation</h1>

  <h2>
    A smart peer to peer video web application
  </h2>
   <div>
      <% if current_user %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in", class: "btn btn-lg btn-primary" %>
      <% end %>
    </div>
</div>
<%= image_tag("Shape-Lightning-25.png", alt: "Lightning logo") %>

app/views/static_pages/new_group.html.erb
<div class="center jumbotron">
  <h1>Welcome to Benedictation</h1>

  <h2>
    A smart peer to peer video web application
  </h2>
   <div>
      <% if current_user %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in", class: "btn btn-lg btn-primary" %>
      <% end %>
    </div>
</div>
<%= image_tag("Shape-Lightning-25.png", alt: "Lightning logo") %>

app/views/static_pages/video.html.erb
<div class="center jumbotron">
  <h1>Welcome to Benedictation</h1>

  <h2>
    A smart peer to peer video web application
  </h2>
   <div>
      <% if current_user %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in", class: "btn btn-lg btn-primary" %>
      <% end %>
    </div>
</div>
<%= image_tag("Shape-Lightning-25.png", alt: "Lightning logo") %>